# Generated by Django 5.0.6 on 2024-07-17 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
